[package]
name = "melodia"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = "s"
lto = true

[features]
setup_tool = []

[dependencies]
anyhow = "1.0.68"
dirs = "4.0.0"
native-dialog = "0.6.3"
tempfile = "3.3.0"
symlink = "0.1.0"
